### ISSUE TITLE
enforce coding 

### ISSUE THREAD

**Issue by Lomet** [ArdenHide/DeclaringOrderExample#1]
To enforce a coding style during pull requests, you can use a combination of a linter and a Continuous Integration (CI) system. For C#, you can use the .NET analyzers together with GitHub Actions as the CI system.

1. First, create a .editorconfig file in the root directory of your repository with the following content:
```
root = true

[*]
indent_style = space
indent_size = 4
charset = utf-8-bom
trim_trailing_whitespace = true
insert_final_newline = true

[*.cs]
# Order of elements
dotnet_diagnostic.IDE0036.severity = warning
dotnet_diagnostic.IDE0035.severity = warning
dotnet_diagnostic.IDE1006.severity = warning
```
This .editorconfig file enforces the indentation style, size, charset, and trailing whitespaces. Additionally, it enforces the order of elements in C# files.

2. Configure the project to use .NET analyzers. Edit your .csproj file by adding the following:
```
<ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.NetAnalyzers" Version="5.0.3" PrivateAssets="all" />
</ItemGroup>
```

3. Create a GitHub Actions workflow. In your repository, create a folder named .github and a subfolder named workflows. Inside the workflows folder, create a YAML file, such as dotnet-lint.yml, with the following content:
```
name: .NET Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release --no-incremental
```

This GitHub Actions workflow is triggered on push and pull requests to the main branch. It sets up the .NET environment, restores dependencies, and builds the project. Any warnings or errors from the analyzers will be displayed during the build step, and the workflow will fail if there are any issues.

With these configurations, your project will enforce a consistent coding style on pull requests. If there are any violations, the build step in the GitHub Actions workflow will fail, and you can address the issues before merging the changes.
